version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/crm_db
      - JWT_SECRET=your-super-secret-jwt-key-here
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=crm_db
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: